spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ktalk
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email, https://www.googleapis.com/auth/youtube.readonly

youtube:
  api-key: ${YOUTUBE_API_KEY}  # 환경 변수로 변경

gemini:
  api-key: ${GEMINI_API_KEY}
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

server:
  port: 8080